spring.data.mongodb.host=localhost
spring.data.mongodb.port = 27017
spring.data.mongodb.database=youtube-clone

####### Amazon S3 ######
cloud.aws.credentials.access-key=cloud_aws_access_key
cloud.aws.credentials.secret-key=cloud_aws_secret_key
cloud.aws.sqs.region=us-east-1
cloud.aws.stack.auto=false
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-8j5jaeo24js5nsvi.us.auth0.com/
auth0.audience=http://localhost:8080
#add '/' for auth0.audience property value

auth0.userinfoEndpoint=https://dev-8j5jaeo24js5nsvi.us.auth0.com/userinfo